# Generated by Django 4.2 on 2023-05-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner_app', '0002_alter_shortener_long_url_alter_shortener_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='short_url',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
